# Site settings
title: Nerd4me Blog
header-img: img/home-bg.jpg
email: yondy.chow@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://nerd4me.github.io"
twitter_username: nerd4me
github_username:  nerd4me
facebook_username:  nerd4me
email_username:  yondy.chow@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
